spring:
#  mvc:
#    contentnegotiation:
#      favor-path-extension: false
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  server:
    error:
      include-message: always
      include-binding-errors: always
      include-exception: true
      include-stacktrace: always
  logging:
    level:
      org.hibernate.SQL: DEBUG
      org.hibernate.type.descriptor.sql: TRACE
      org.springframework: DEBUG
      org.springframework.web: DEBUG
      org.thymeleaf: TRACE
    spring:
